# _config.yml
name: hexo-theme-animal
version: 1.0.0

author: 崴寶 Weibert Weiberson 
title: 崴寶 Weibert Weiberson Template

custom:
  logo: /images/2.png
  logo2: /images/0.gif
  home_intro_img: /images/1.png
  wellcome1: "歡迎來到Weiberson Chang的網站！"
  wellcome2: "在這裡你可以看到我做的模板，想更認識我也可以來我Github或Medium唷。"

menu:
  GitHub1: "https://github.com/weitsung50110"
  GitHub2: "GitHub"
  GitHub_logo: "/images/github.png"
  Medium1: "https://medium.com/@weiberson"
  Medium2: "Medium"
  Medium_logo: "/images/medium.png"
  Instagram1: "https://www.instagram.com/weiberson_blog/"
  Instagram2: "IG"
  Instagram_logo: "/images/ig.png"

sidebar:
  Author_photo: /images/a1.jpg
  Author: "Weiberson Chang"
  Auther_descrip: "(Wei Tsung Chang)"
  other: "Master of Computer Science / AI Software Engineer"
  website: "https://weitsung50110.github.io/"
  website_btn: "崴寶 Weibert Weiberson"
