# _config.yml
name: hexo-theme-animal
version: 1.0.0

author: å´´å¯¶ Weibert Weiberson 
title: å´´å¯¶ Weibert Weiberson Template

custom:
  logo: /images/2.png
  logo2: /images/0.gif
  home_intro_img: /images/1.png
  wellcome1: "æ­¡è¿ä¾†åˆ°Weiberson Changçš„ç¶²ç«™ï¼"
  wellcome2: "åœ¨é€™è£¡ä½ å¯ä»¥çœ‹åˆ°æˆ‘åšçš„æ¨¡æ¿ï¼Œæƒ³æ›´èªè­˜æˆ‘ä¹Ÿå¯ä»¥ä¾†æˆ‘Githubæˆ–Mediumå”·ã€‚"

menu:
  GitHub1: "https://github.com/weitsung50110"
  GitHub2: "GitHub"
  GitHub_logo: "/images/github.png"
  Medium1: "https://medium.com/@weiberson"
  Medium2: "Medium"
  Medium_logo: "/images/medium.png"
  Instagram1: "https://www.instagram.com/weiberson_blog/"
  Instagram2: "IG"
  Instagram_logo: "/images/ig.png"

sidebar:
  Author_photo: /images/a1.jpg
  Author: "å´´å¯¶"
  Auther_descrip: "(Weibert Weiberson)"
  other: "Master of Computer Science / AI Software Engineer"
  website: "https://weitsung50110.github.io/"
  website_btn: "å´´å¯¶ Weibert Weiberson"

float:
  toc: "ğŸ“–"
  scroll_to_top: "â–²"
  side_bar: "ğŸ¤—"